# I am struggling with getting the list to work
- hosts: localhost
  tasks:
  - name: All the libraries i love
    become: true
    apt:
      name: fzf
      state: present
    vars:
      packages:
      - fzf
      - ripgrep
      - pavucontrol
      - xclip
      - jq
      - tldr
      - shutter
    loop_control:
      loop_var: package
    with_items: "{{ packages }}"
